export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_AUTO_LOGIN = 'AUTH_AUTO_LOGIN';

export const SET_CURRENT_USER = 'CURRENT_USER';
export const SET_USERS = 'SET_USERS';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAIL = 'USER_FAIL';

export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_FAILED = 'SET_PROFILE_FAILED';

export const SET_FEEDS = 'SET_FEEDS';
export const FEED_FAIL = 'FEED_FAIL';
export const FEED_SUCCESS = 'FEED_SUCCESS';


export const SET_FEED_LIKES = 'SET_FEED_LIKES';
export const FETCH_LIKES_FAIL = 'FETCH_LIKES_FAIL';

export const SET_FEED_COMMENTS = 'SET_FEED_COMMENTS';
export const SET_FEED_LATEST_COMMENTS = 'SET_FEED_LATEST_COMMENTS';
export const COMMENT_FETCH_FAIL = 'COMMENT_FETCH_FAIL';
export const COMMENT_FETCH_SUCCESS = 'COMMENT_FETCH_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const SET_COMMENT_REPLIES = 'SET_COMMENT_REPLIES';
export const SET_COMMENT_LATEST_REPLIES = 'SET_COMMENT_LATEST_REPLIES';
export const REPLY_FETCH_FAIL = 'REPLY_FETCH_FAIL';
export const REPLY_FETCH_SUCCESS = 'REPLY_FETCH_SUCCESS';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
export const ADD_REPLY_FAIL = 'ADD_REPLY_FAIL';
